name: docker deployment
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker image build
        run: docker build -t ${{vars.DOCKER_USERNAME}}/food-app:latest .
      - name: docker image tag
        run: docker image tag ${{vars.DOCKER_USERNAME}}/food-app:latest ${{vars.DOCKER_USERNAME}}/food-app:$GITHUB_RUN_NUMBER
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push latest image to docker hub
        run: docker push ${{vars.DOCKER_USERNAME}}/food-app:latest
      - name: push tagged image for backup
        run: docker push ${{vars.DOCKER_USERNAME}}/food-app:$GITHUB_RUN_NUMBER
       # $GITHUB_RUN_NUMBER - github predefined environment variable 
      
  old-deployment:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Remove COntainer
        run: docker container rm -f ${{vars.CONTAINER_NAME}}
      - name: remove old image
        run: docker rmi ${{vars.DOCKER_USERNAME}}/food-app:latest
  deploy:
    needs: old-deployment
    runs-on: self-hosted
    steps:
      - name: pull the image
        run: docker pull ${{vars.DOCKER_USERNAME}}/food-app
      - name: run the container
        run: docker container run -dt --name ${{vars.CONTAINER_NAME}} -p 80:80 ${{vars.DOCKER_USERNAME}}/food-app:latest
      - name: container status
        run: docker container ps -a
