name: Docker Deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/food-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ vars.DOCKER_USERNAME }}/food-app

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull the Docker image
        run: docker pull ${{ vars.DOCKER_USERNAME }}/food-app:latest

      - name: Run the Docker container
        run: docker container run -d --name food-app -p 80:80 ${{ vars.DOCKER_USERNAME }}/food-app:latest

      - name: Check container status
        run: docker ps -a
